name: figanos
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.14
  # Main
  - cartopy >=0.23.0
  - cairosvg >=2.6.0
  - matplotlib-base >=3.6.0
  - seaborn >=0.13.0
  - geopandas >=1.0
  - numpy >=1.25.0
  - pandas >=2.2.0
  - platformdirs >=4.0
  - pint >=0.18
  - pyyaml >=6.0.1
  - scikit-image >=0.21.0
  - xarray >=2023.11.0
  - xclim >=0.52.2
  # Development
  - pip >=25.1
  - black ==25.1.0
  - blackdoc ==0.3.9
  - bump-my-version >=1.0.0
  - coverage >=7.5.0
  - flake8 >=7.1.1
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.10.1,<4.0.0
  - isort ==6.0.1
  - mypy >=1.14.1
  - numpydoc >=1.8.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - ruff >=0.9.0
  - tox >=4.24.1
  - watchdog >=4.0.0
  # Notebooks
  - dask
  - geoviews
  - h5py
  - holoviews
  - netcdf4
  - pooch >=1.8.0  # for xclim-testdata
  - zarr >=2.13.0
  # Docs
  - ipykernel
  - ipython >=8.5.0, !=9.0.0
  - jupyter_client
  - nbsphinx >=0.9.5
  - notebook
  - sphinx >=7.0.0,<8.2.0  # pinned until nbsphinx is updated to support Sphinx 8.2
  - sphinx-book-theme >=1.0.0
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
