name: figanos
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11,<3.15
  # Main
  - cartopy >=0.23.0
  - cairosvg >=2.6.0
  - matplotlib-base >=3.8.0
  - seaborn >=0.13.0
  - geopandas >=1.0
  - numpy >=1.25.0
  - pandas >=2.2.0
  - platformdirs >=4.0
  - pint >=0.18
  - pyyaml >=6.0.1
  - scikit-image >=0.21.0
  - xarray >=2023.11.0
  - xclim >=0.52.2
  - xsdba >=0.4.0
  # Development
  - pip >=25.2
  - bump-my-version >=1.2.3
  - coverage >=7.5.0
  - deptry >0.23.0
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.18.2
  - numpydoc >=1.9.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - ruff >=0.13.3
  - tox >=4.30.3
  - vulture >=2.14
  - watchdog >=4.0.0
  # Notebooks
  - dask
  - geoviews
  - h5py
  - holoviews
  - netcdf4
  - pooch >=1.8.0  # for xclim-testdata
  - zarr >=2.13.0
  # Docs
  - ipykernel
  - ipython >=8.5.0, !=9.0.0
  - jupyter_client
  - nbsphinx >=0.9.8
  - notebook
  - sphinx >=8.2.0
  - sphinx-book-theme >=1.0.0
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-intl
